version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  bonus-service:
    build:
      context: bonusService
    depends_on:
      - postgres
    ports:
      - "8050:8050"

  flight-service:
    build:
      context: flightService
    depends_on:
      - postgres
    ports:
      - "8060:8060"

  ticket-service:
    build:
      context: ticketService
    depends_on:
      - postgres
    ports:
      - "8070:8070"

  gateway:
    build:
      context: gateway
    ports:
      - "8080:8080"
    depends_on:
      - bonus-service
      - flight-service
      - ticket-service
volumes:
  db-data: