spring:
  flyway:
    baselineOnMigrate: true
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres-service:5432/privileges
    username: program
    password: test
