spring:
  flyway:
    baselineOnMigrate: false
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/flights
    username: program
    password: test
