name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      # Application
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build images
        run: docker-compose build

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Push
        run: |
          cd ./scripts
          chmod +x create-push-images.sh
          ./create-push-images.sh

      - name: Install Kubectl
        uses: Azure/setup-kubectl@v3.1

      - name: Create .kube folder
        run: mkdir $HOME/.kube

      - name: Send YC config to K8S
        run: cp ./k8s/config $HOME/.kube/config

      - name: Deploy DB to YC
        run: helm install databases k8s/postgres-chart

      - name: Deploy Services to YC
        run: helm install services k8s/rsoi4-chart

      - name: Wait 45 seconds
        run: sleep 45

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"